* Chapter
** Invitation
   
Since its inception in 1994, Lean Construction has fundamentally revolved around theoretical and practical aspects associated with the new production management theory into the AEC industry. Thus, the perception that Lean Construction was a simple extension of Lean Manufacturing principles in construction has changed as this has been established as a production management theory in its own right incorporating new fields to its body of knowledge such as planning and control, organization, culture and people, supply chain, information technologies, teaching and education, sustainability and safety, design and cost management, procurement and contract management, lean in the public sector. 
This has been the result of transformational changes in Lean Construction research and implementation across the globe over the last 25 years that has concluded in the realization that the most significant triad in today’s business is the one composed of people, processes, and technology, with all that this nexus entails.
In the 70’s, automation changed how different operations from order request and billing to CAD and manufacturing took place increasing dramatically productivity. In the 80’s, the advent of the “Internet” enabled integration levels never seen before across the supply chain (locally and globally). Nowadays, the advent of “fourth industrial revolution” with its associated technologies such cyber physical systems, mixed-reality, internet of things (IoT), cloud computing, artificial intelligence (AI), mixed-reality, and its impact on the AEC industry, is demanding a rethinking of the role of Lean Construction as a driver of ongoing improvement with reduction of waste and increase of value at its core. In fact, the capability of Lean Construction to effectively adapt to this new era full of digital changes requires a reconceptualization of the triad people-processes-technology within the theoretical and practical framework of Lean Construction. Therefore, a shift towards Lean Construction 4.0 is required.
Lean Construction 4.0 as a new systems-wide thinking where synergies and overlaps between Lean Construction and digital/smart technologies goes far beyond BIM, and how this concept will reshape the way we design, manage, and operate capital projects in the modern age of automation. On reflection, researchers around the world have touched timidly different aspects of Lean Construction and digital/smart technologies. Our aim for this call for contributions from international experts at the interface of Lean Construction and digital/smart technologies is to channel research efforts to generate an edited book on Lean Construction 4.0 and discuss current research and practice, challenges and drivers, and future perspectives of Lean Construction 4.0. We are in discussions with Taylor and Francis about publishing the book, who are excited about this project. Dr Vicente A. Gonzalez (University of Auckland), Assoc. Prof. Farook Hamzeh (University of Alberta), and Prof. Luis Fernando Alarcon (Pontificia Universidad Catolica de Chile) are pleased to invite become a contributor in one of the chapters of the “Lean Construction 4.0” Book.

*** Questions to be addressed by authors in proposed chapters. 
****  If you are interested in authoring one of the Chapters of the Lean Construction 4.0 book, we would like to consider the following questions to guide the development of your chapter:
    1. How do you think lean construction principles are linked to the technology functionalities/features of the digital/smart technology that you investigated and worked with? This would produce what we name as “Lean Construction 4.0”
    2. How do you think the duality lean/technology connect with people in practical terms? Please think in different aspects such as implementation and adoption, end-users usability issues.
    3. What do you think are the main barriers and challenges to implement “Lean Construction 4.0” in industry? What do you think are the gains and overall benefits?
    4. How can we educate students on the challenges and benefits of “Lean Construction 4.0”?
    5. How can we avoid the temptation of placing technology at the core rather than people when we think about the “Lean Construction 4.0” concept?
    6. Framework proposed for chapters: We would also like that authors consider the following framework for the chapters. While we don’t want to constraint innovation and creative in the making of the chapters, we hope that this can be the minimum technical aspects to be covered.

*** Theoretical underpinning
    - Technology
    - People
    - Research methodological approach
    - Discussion on how lean principles are supported by the suggested technology
    - How do we apply this?
    - Benefits and impacts

*** What we expect from contributors that accept to co-author a chapter in the book at this point:

A 250 words-abstract answering the questions proposed above, describing how a proposed chapter will look like within the Lean Construction 4.0 book.
A chapter outline based on the previously mentioned framework.

*** Deadline:
    We understand that we are facing an unprecedented challenge with COVID-19, but we also believe that one of the things that will help to go through this crisis successfully is to keep doing what we know best: Thinking, creating, innovating, communicating and writing about science in construction engineering and management. This proposal is to keep going with all of that. So, if you are willing to contribute with this exciting project, please submit the abstract and chapter outline to the editors of the book: v.gonzalez@auckland.ac.nz , hamzeh@ualberta.ca, and lalarcon@ing.puc.cl by June 30th, 2020.´
** WORKING Outline

*** CANCELLED COMMENT Free outline
**** Lack of a production theory
***** How manufacturing deals with production
***** Why it isn't a literal translation
**** The concept of setups in projects
**** Modelling processes
**** What the model tell us
**** Educated guess: Forecast and control
**** Applicability

    
*** Technical aspects
**** WORKING Theoretical underpinning
     The building construction industry faces challenges, such as increasing project complexity and scope requirements, but shorter deadlines. Additionally, economic uncertainty and rising business competition with a subsequent decrease in profit margins for the industry demands the development of new approaches to construction management. However, the building construction sector relies on practices based on intuition and experience, overlooking the dynamics of its production system. Furthermore, researchers maintain that the construction industry has no history of the application of mathematical approaches to model and manage production. 

Much work has been carried out on how manufacturing practices apply to construction projects, mostly lean principles. Nevertheless, there has been little research to understand the fundamental mechanisms of production in construction. 

This researchs develops an in-depth literature review to examine the existing knowledge about production models and their characteristics in order to establish a foundation for dynamic production systems management in construction. As a result, a theoretical framework is proposed, which will be instrumental in the future development of mathematical production models aimed at predicting the performance and behaviour of dynamic project-based systems in construction.
**** WORKING Technology
     Such modelling approach requires computational aid. Despite calculations are relatively effortles to current computation power, the data aquisition of an integrated system requires several techniques.
# TODO: Mention some technologies from Envision... 
 This paper suggests a framework to address production issues on construction by implementing an integrated automatic supervisory control and data acquisition for management and operations. The system is divided into planning, monitoring, controlling, and executing groups clustering technologies to track both the project product and production.


**** WORKING People
     

**** Research methodological approach

**** WORKING Discussion on how lean principles are supported by the suggested technology
     This research stands on the four pillars of manufacturing knowledge and lean production (production processes, production management, equipment/tool design, and automated systems and control). The framework offers benefits such as increased information flow, detection and prevention of overburdening equipment or labor (Muri - 無理) and production unevenness (Mura - 斑), reduction of waste (Muda - 無駄), evidential and continuous process standardization and improvement, reuse and abstraction of project information across endeavors.

**** WORKING How do we apply this?
     The project-driven production management sees production as a system, with inputs to a process that will create outputs.
As such, a system may comprehend an activity (process), which is driven by resources or labor (inputs) to generate

an important activity, or an 



By defining the system and periodically measuring inputs and outputs

**** WORKING Benefits and impacts
The contribution to the body of knowledge of this thesis is a new view of production in project-driven processes in construction. This system view is founded on the relation between cause and consequence described by the manipulation of inputs to control the process's output as in a dynamic system. This relation can now be determined with a higher accuracy than can be obtained using traditional steady state methods. By considering the transient state and the steady, or unsteady, state, the Productiv- ity Function may cornerstone on the understanding of the dynamics of production in construction and on the development of a mathematical foundation for the manage- ment of project-driven production. For instance, the measurement of transient time supports the application of SMED practices in construction processes, which increase productivity by reducing setup times. On the other hand, being able to calculate the throughout at capacity of processes allow the calculation of productivity loss, benchmarking of processes, and supports the management of these processes. For instance, on ?emergency situations, processes with shorter transients are preferable once they can quickly reach high throughput, for instance, temporary bridges constructed for evacuation. On the other hand, for long runs, processes with high throughput at steady-state may be more desirable as in the case of the use of tunnel boring machines (TBM) which have long setup times but high productivity at steady-state.

This research also contributed to the Construction Management body of knowl-
edge by providing a set of analytical equations towards a mathematical production theory for project-driven processes. This mathematical production theory not only points out production parameters in construction processes that were previously unmeasurable, e.g., transient time and capacity but also provide a framework for con- trolling the processes. The outcome of this study directly applies to the management of supply chain or processes arranged in a chain as a tool for benchmarking, plan- ning, monitoring, and control. It can also be applied to isolated processes but with diminished bene?ts. For instance, by comparing the cycle times of two processes, a manager can determine that a process with much lower cycle times than a precedent one will have idle resources even when the precedent operates near capacity. Based on this information, managers can allocate resources to balance the productivity of the processes. Moreover, this resource balance and process control can be performed au- tomatically using the Productivity Model Predictive Control. In a chain of processes, the better control allows smaller bu?ers between the processes. With better control and more predictable performance, the slack between processes can be reduced. Results show that the controlling approaches can achieve high process performances even when operating closer to capacity. Better tracking and control allows the process to operate closer to capacity, consequently, achieving higher productivity. Altogether, it is possible to increase production without increasing resources. That immediately results in cost reduction. In similar fashion, the Productivity Function can be used in dynamics simulation
which is based on ordinary di?erential mathematical models. Dynamics simulation has a signi?cant role in the supply chain but is rarely applied in construction due to the lack of suitable mathematical models to describe the production in construction. These models can now be generated easily, consequently enabling the application of Dynamics Simulation in production. Understanding Understanding production mechanisms in conjunction with systematic methods will enable the use of means-ends analysis in project-driven production systems. Construction processes could be simulated with higher accuracy and with control approaches closer to the reality of those used by managers. Furthermore, the integration of production mechanisms with means-ends analysis provides a system view supporting the identi?cation of production issues via model iteration bene?cial to project management especially risk management and decision-making.


     This research builds an analytical and scalable method (Productivity Function) to represent the behavior of production systems. By considering the transient state, Productivity Function produced models that were more accurate in describing the processes dynamics than the steady state approaches. The Productivity Function provides a mathematical foundation to develop algebraic for the calculations of cycle times (average, best- and worst-cases), throughput at capacity, and the influence of the transient state time in the production variability. Productivity Function is applied in feedback loop control yielding a robust approach to plan, control, and optimize production.


** DONE Answers [100%]  
*** DONE How do you think lean construction principles are linked to the technology functionalities/features of the digital/smart technology that you investigated and worked with? This would produce what we name as “Lean Construction 4.0”

    This theory stands on the four pillars of manufacturing knowledge and lean production: production processes, production management, equipment/tool design, and automated systems and control.
The production processes, in this case, project-driven processes, are divided into planning, monitoring, controlling, and executing groups clustering technologies to track both the project product and production.
The research translates production management theory (e.g., variability and capacity) to project-driven production management.
As such, to mathematically determine a process model and its features, a novelty approach was developed: the Productivity Function.
The Productivity Function deals with project-driven production processes as a system structured as input(s) → processes → output(s). Information collection of input(s) and output(s) is crucial to calculate the process. As such, the project management automated system and control utilizes a series of techniques such as computer vision, artificial intelligence, and internet-of-things (IoT) to collect data.

*** DONE How do you think the duality lean/technology connect with people in practical terms? Please think in different aspects such as implementation and adoption, end-users usability issues.

    The theory aims to offer benefits such as increased information flow, detection and prevention of overburdening equipment or labor (Muri - 無理) and production unevenness (Mura - 斑), reduction of waste (Muda - 無駄), evidential and continuous process standardization and improvement, reuse and abstraction of project information across endeavors. End-users need to understand the concepts of production management and their application to project management. 
In summary, it is a quantitative application of lean manufacturing theory to construction management.

*** DONE What do you think are the main barriers and challenges to implement “Lean Construction 4.0” in industry? What do you think are the gains and overall benefits?

    On a project management dayly basis collect and process information is challenging. Information is inaccurate often provenient from guesses instead of measurement. Process information into knowledge is then discouraged or outcome into to also innacurate results. What may support incorrect decision. In manufacturing, the operation is constantly monitored by the supervisory control and data acquisition (SCADA) system. The system monitors, gathers, and processes real-time In manufacturing, the production moves from machine to machine, worker to worker, or a combination of both. The route of production is fixed (Antunes and Gonzalez 2015; Hayes and Wheelwright 1979). Thus, the positions of sensors and actuators are fixed and planned according to the production routes and its flow. Once set, the positions only need to be modified if the production routes change. In construction production routes are flexible. “Jobs arrive in different forms and require different tasks, and thus the equipment tends to be relatively general purpose (Hayes and Wheelwright 1979).” Some production routes will only exist long after the beginning of the project by the time that others would be extinct. Construction must then rely on general purpose sensors that, as the equipment, can be used in different applications through the project life-cycle, often, requiring those also to be mobile. Hence, traditional instrumentation (and sensor positioning) used in a manufacturing SCADA systems do not work in construction, as the instrumentation must be mobile.

*** DONE How can we educate students on the challenges and benefits of “Lean Construction 4.0”?

    From this theory, students will acquire concepts and methods as well as learn how to calculate and apply to a variety of project scenarios. It the end, students will have to make management decisions supported by calculations using the project data. It starts with concepts from production management in manufacturing cite:Hopp1990, and an overview of dynamic systems cite:Nise2010. From this point forward, you will model project production based on data, calculate different parameters, and use them in your decision-making process. Students should also be familiar with basic data science and programming in Matlab or Python. Students also should expect to work with different disciplines in a project-based learning approach that will challenge your problem-solving skills.

*** DONE How can we avoid the temptation of placing technology at the core rather than people when we think about the “Lean Construction 4.0” concept?
    The theory, as well as the automated support system, aims to support project managers' decision-making process and project processes execution. 
The data and the theory  tends to eliminate informal processes 
as these are continuously monitored and assessed.
Moreover, the data (from production progress and workers' effort) generate a process history and benchmark for future projects.
That creates the opportunity for continuous improvement in project-driven production.
Thus, managers can develop and standardize better processes. 
Companies will quantitatively assess and qualify the performance of contractors in previous projects. 
In an intensive third-party contracting industry such as construction, low productivity companies that often make mistakes are costly, and consequently, placed at the end of the supplier’s list or excluded. 
Construction needs an increase in the number of builders. 
Most importantly, the industry needs builders with better performance.

** DONE Paper Abstracts
**** A Production Model for Construction: A Theoretical Framework
     The building construction industry faces challenges, such as increasing project complexity and scope requirements, but shorter deadlines. Additionally, economic uncertainty and rising business competition with a subsequent decrease in profit margins for the industry demands the development of new approaches to construction management. However, the building construction sector relies on practices based on intuition and experience, overlooking the dynamics of its production system. Furthermore, researchers maintain that the construction industry has no history of the application of mathematical approaches to model and manage production. Much work has been carried out on how manufacturing practices apply to construction projects, mostly lean principles. Nevertheless, there has been little research to understand the fundamental mechanisms of production in construction. This study develops an in-depth literature review to examine the existing knowledge about production models and their characteristics in order to establish a foundation for dynamic production systems management in construction. As a result, a theoretical framework is proposed, which will be instrumental in the future development of mathematical production models aimed at predicting the performance and behaviour of dynamic project-based systems in construction.
**** Identification of repetitive processes at steady- and unsteady-state: Transfer function
     Projects are finite terminating endeavors with distinctive outcomes, usually, occurring under transient conditions. Nevertheless, most estimation, planning, and scheduling approaches overlook the dynamics of project-based systems in construction. These approaches underestimate the influence of process repetitiveness, the variation of learning curves and the conservation of processes' properties. So far, estimation and modeling approaches have enabled a comprehensive understanding of repetitive processes in projects at steady-state. However, there has been little research to understand and develop an integrated and explicit representation of the dynamics of these processes in either transient, steady or unsteady conditions. This study evaluates the transfer function in its capability of simultaneously identifying and representing the production behavior of repetitive processes in different state conditions. The sample data for this research comes from the construction of an offshore oil well and describes the performance of a particular process by considering the inputs necessary to produce the outputs. The result is a concise mathematical model that satisfactorily reproduces the process' behavior. Identifying suitable modeling methods, which accurately represent the dynamic conditions of production in repetitive processes, may provide more robust means to plan and control construction projects based on a mathematically driven production theory.
**** Dynamics of Project-Driven Production Systems in Construction: Productivity Function
     Mathematical models have historically enabled a thorough understanding of production mechanisms in manufacturing supporting actions and laws to improve fabrication and building performance. Although much work has been done to date on modeling of production processes, more studies need to be conducted to understand the dynamics of these processes and develop mathematical relationships and laws that can reliably predict and manage project-driven production systems in construction. The purpose of this research is to explore the hypothesis that production processes in construction can be represented as dynamic systems in which a productivity function describes the time dependence of the systems’ output–input relation. By considering the transient state, productivity function models were more accurate in describing the process dynamics than first-degree polynomials and the arithmetic mean, confirming the hypothesis. The contribution of this research to the body of knowledge is a newmodel that considers different states of project-driven processes.
**** Quicker reaction, lower variability: The effect of transient time in flow variability of project-driven production
     Based on the knowledge of dynamic systems, the shorter the transient response, or the faster a system reaches the steady-state after the introduction of the change, the smaller will be the output variability. In lean manufacturing, the principle of reducing set-up times has the same purpose: reduce the transient time and improve production flow. Analogously, the analysis of the transient response of project-driven systems may provide crucial information about how fast these systems react to a change and how that change affects their production output. Although some studies have investigated flow variability in projects, few have looked at variability from the perspective that the transient state represents the changeovers on project-driven production systems and how the transient state affects the process’ flow variability. The purpose of this study is to investigate the effect of changes in project-driven production systems from a conceptual point of view, furthermore, measuring and correlating the transient response of five cases to their flow variability. Results showed a proportional relationship between the percentile transient time and flow variability of a process. That means that the quicker the production system reacts to change; the less the distress in the production output, consequently, lower levels of flow variability. As practical implications, lean practices focusing on reducing set-up times (transient time) can have their effects measured on project-driven production flow.
**** Benchmarking Project-Driven Production in Construction Using Productivity Function: Capacity and Cycle Time
     Despite being inaccurate, linear models are often used by construction managers to describe production, which limits the develop- ment and application of a production theory. The objective of this study is to formulate and test new equations comprehending the non-steady- state conditions of repetitive project-driven processes in construction to calculate cycle time and capacity based on productivity function models. The algebraic calculations were developed from Little’s Law to estimate cycle times and capacity and then tested on productivity function models of 11 construction processes (two cases arranged in a supply chain). It has been reaffirmed that the transient time negatively impacts process productivity. The transient time and theoretical average cycle time showed a proportional relationship to the average cycle times of the samples, resulting in a benchmarking ranking close to the one measured. This study contributes to the body of knowledge by introducing equations for capacity and cycle time based on a process productivity function model that can be used on processes in any state. It can be an alternative to three-point estimation, for instance.
**** Productivity Function Predictive Control to takt time on project-driven production in construction
     High throughput variability prevents the application of methods that rely on steady cycle times, such as takt time. Lacking an objective control method, production in construction often depends on the manager’s intuition and improvisation. The goal of this study is to verify two automatic control strategies in their ability to increase the throughput of construction processes while keeping a steady throughput. Proportional-integral-derivative (PID) control and model predictive control (MPC), both using Productivity Func- tion models, were applied to a set of isolated and connected processes from a housing project. Results showed that the controlling approaches were successful in achieving higher performances than the original data, even under tougher constraints. Furthermore, the predictive control has shown superior performance than the reactive approach. MPC has shown to be useful in construction due to its proactive characteristic, use of constraints, and performance in a flow. Those, features that support the implementation of takt time.
**** Envision of an Integrated Information System for Project-driven Production in Construction
     Construction frequently appears at the bottom of productivity charts with decreasing indexes of productivity over the years. Lack of innovation and delayed adoption, informal processes or insufficient rigor and consistency in process execution, insufficient knowledge transfer from project to project, weak project monitoring, little cross-functional cooperation, little collaboration with suppliers, conservative company culture, and a shortage of young talent and people development are usual issues. Whereas work has been carried out on information technology and automation in construction their application is isolated without an interconnected information flow. This paper suggests a framework to address production issues on construction by implementing an integrated automatic supervisory control and data acquisition for management and operations. The system is divided into planning, monitoring, controlling, and executing groups clustering technologies to track both the project product and production. This research stands on the four pillars of manufacturing knowledge and lean production (production processes, production management, equipment/tool design, and automated systems and control). The framework offers benefits such as increased information flow, detection and prevention of overburdening equipment or labor (Muri - 無理) and production unevenness (Mura - 斑), reduction of waste (Muda - 無駄), evidential and continuous process standardization and improvement, reuse and abstraction of project information across endeavors.
**** Dynamics of project-driven systems: A production model for repetitive processes in construction
The building construction industry faces challenges, such as increasing project complexity and scope requirements, but shorter deadlines. Additionally, economic uncertainty and rising business competition with a subsequent decrease in profit margins for the industry demands the development of new approaches to construction management. However, the building construction sector relies on practices based on intuition and experience, overlooking the dynamics of its production system. These approaches underestimate the influence of process repetitiveness, the size of the production run, the transient state, the variation of learning curves, and the conservation of processes properties. At this time, construction adopts the manufacturing production model dismissing the application of mathematical approaches that accurately describe the characteristics of its production system. The current theory about fundamental mechanisms of production in repetitive processes in construction is at an embryonic stage and does not yet fully establish the foundations of a production model. The aim of this research is to provide a mathematical model to describe and understand the production mechanisms of repetitive processes in project-driven systems in construction, moreover, applying the model to project management. This study begins with an in-depth literature review to examine the existing knowledge about production models and their characteristics to establish a theoretical framework for controlling dynamic production systems management in construction. On this framework, this research builds an analytical and scalable method (Productivity Function) to represent the behavior of production systems. By considering the transient state, Productivity Function produced models that were more accurate in describing the processes dynamics than the steady state approaches. The Productivity Function provides a mathematical foundation to develop algebraic for the calculations of cycle times (aver- age, best- and worst-cases), throughput at capacity, and the influence of the transient state time in the production variability. Productivity Function is applied in feedback loop control yielding a robust approach to plan, control, and optimize production.
