#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+OPTIONS: author:t broken-links:nil c:nil creator:nil
#+OPTIONS: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:t
#+OPTIONS: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+OPTIONS: timestamp:t title:t toc:t todo:nil |:t
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 26.3 (Org mode 9.1.9)


#+LATEX_COMPILER: pdflatex
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS:
#+LATEX_HEADER: \usepackage[a4paper,bindingoffset=0.2in,left=1in,right=1in,top=1in,bottom=1in,footskip=.25in]{geometry}
#+LATEX_HEADER_EXTRA:
#+TITLE: Productivity Function - Mathematical foundation for Production Management in Construction
#+SUBTITLE:
#+AUTHOR: Ricardo Antunes, Vicente A. González, Kenneth Walsh, Michael O'Sullivan, and Omar Rojas

#+DESCRIPTION: Chapter Proposal
#+KEYWORDS:
#+DATE: \today

* Guidelines
#+begin_src emacs-lisp
  (tex-count-word)
#+end_src
  - 7000 Words
* Book Chapter
** DONE Abstract
   :LOGBOOK:
   CLOCK: [2020-06-23 Tue 20:08]--[2020-06-23 Tue 20:33] =>  0:25
   :END:

The building construction industry faces challenges, such as increasing project complexity, and larger scope requirements but shorter deadlines. 
Additionally, the industry relies on practices based on intuition and experience, overlooking the dynamics of its production system. 
These approaches underestimate the influence of process repetitiveness, the size of the production run, the transient state (setup times), the variation of learning curves, and the conservation of processes properties. 
Consequently, construction adopts the manufacturing production model dismissing the application of approaches that accurately describe the characteristics of its production system. 
This chapter aims to provide a production theory to better understand the production mechanisms of repetitive processes in project-driven systems in construction.
The chapter begins with an examination of the existing knowledge about production models, their characteristics, and the challenges to establishing a theoretical framework for controlling dynamic production systems management in construction projects. 
The chapter progresses to an analytical and scalable method (Productivity Function) to represent the behavior of production systems. 
The Productivity Function provides a mathematical foundation for the calculations of cycle times (average, best- and worst-cases), throughput at capacity, and the influence of the transient state time in the production variability. 
Productivity Function is applied in feedback loop control yielding a robust approach to plan, control, and optimize production.
Finally, the chapter presents automated methods of data collection that feed the Productivity Function models, which are the foundation of the production theory and support the decision-making process on Lean Construction 4.0. 

** INBOX Outline
**** Introduction
**** Lean principles and production theory
***** Production in manufacturing (Factory Physics)
      The manufacturing industry is knowable of its production.
      From early times when 'time and motion' has been developed on workers construction a brick wall (Reference here), manufacturing has being advancing on undestanding and manageming of its production.
      Mostly important on the context on this book, it was the creation and development of lean production that inspired lean construction.
      This chapter stands on further development of lean production: it's mathematical explanation of production.
     Such work has been conducted by TOYOTA dude, THE guy from MIT and mates from Factory Physics.
     Their work combined provide a set of equations that apply to manufacturing production systems.
     A production system consists into three main elements: inputs, process, outputs (Figure ).
     Inputs may not reflecet the full range of requirementes to create the output but on this system view they determine the output.
     The process can be determined on physical knwon equations or most oftern determined by evaluating the relationship betwen input and output.
     The mathematical representation of this relantionship is main difference between manufacturing and construction.
***** The manufacturing theory does not apply directly to construction
      Manufacturing is either a continous or a repective process.
      Machinery and human resources are specialized and qualified.
      Production flow and material routes are established. 
      Thus, most manufacturing processess can be automated.
      That scenario is different from construction.

      While capacity is knwon and measured in manufacturing, there was no way to measured it in construction.
      Increasing production in construction often means add more human resources.
      That often cause decrease of productivity due to lack of space, tools, skills, etc.
      
**** Productivity Function
****** Production process system representation
****** Mathematical foundation of the Productivity Function
****** Modelling method
**** Production Theory for Construction
****** Production forecast
****** Variability analysis
****** Production benchmark
******* Capacity
******* Throughput
******* Cycle-time
******** Average cycle-time
******** Worst cycle-time
******** Best cycle-time
****** Production plan, monitoring, and control
**** Applicability
***** Automation and technology
****** Supervisory control and data acquisition (SCADA)
****** Challenges
***** Decision-making support
***** Benefits and impacts
**** Discussion
**** Conclusion
**** References
     
