(TeX-add-style-hook
 "chapter"
 (lambda ()
   (TeX-add-to-alist 'LaTeX-provided-package-options
                     '(("inputenc" "-*-coding:utf-8-*-") ("fontenc" "T1") ("ulem" "normalem") ("geometry" "margin=2cm" "a4paper" "bindingoffset=0.2in" "left=1in" "right=1in" "top=1in" "bottom=1in" "footskip=.25in") ("biblatex" "backend=biber" "style=apa" "backend=bibtex" "style=authoryear" "alldates=year" "sorting=nyt")))
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "href")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperref")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperimage")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperbaseurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "nolinkurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "path")
   (TeX-run-style-hooks
    "latex2e"
    "article"
    "art10"
    "inputenc"
    "fontenc"
    "graphicx"
    "grffile"
    "longtable"
    "wrapfig"
    "rotating"
    "ulem"
    "amsmath"
    "textcomp"
    "amssymb"
    "capt-of"
    "hyperref"
    "geometry"
    "biblatex"
    "tikz")
   (LaTeX-add-labels
    "sec:org8caad99"
    "sec:orgafad2cd"
    "sec:org49c7f3c"
    "sec:org5270d33"
    "sec:org7a498ec"
    "throughput"
    "sec:org44c8dd4"
    "capacity"
    "sec:orgf81889f"
    "work-in-process"
    "sec:orgd1b3533"
    "cycle_time"
    "sec:org9fd8ed7"
    "lead_time"
    "sec:org7608a8d"
    "utilization"
    "sec:orgc5d3ec2"
    "littles_law"
    "sec:org3b63288"
    "fig:org229e7eb"
    "fig:orgb843958"
    "eq:Little's Law for operation management"
    "sec:orgafc56d2"
    "sec:orgfe22a93"
    "eq:Critical_WIP"
    "sec:orgaefb431"
    "sec:orgfbc9f3b"
    "fig:orga6be94c"
    "fig:orgba9ce4d"
    "sec:org7d3de97"
    "sec:orgd9084f7"
    "sec:org286e063"
    "sec:orgb1677aa"
    "sec:org926869d"
    "fig:orgf80a82c"
    "sec:orgd6b7c76"
    "sec:org4c75e49"
    "sec:orgea4d9e0"
    "fig:org4299d59"
    "fig:org34e96d7"
    "fig:org2810aec"
    "sec:org50e188d"
    "sec:org3e47b41"
    "eq:steady state"
    "eq:Step function in time domain P7"
    "sec:orge2dcfb7"
    "sec:orgcfbff11"
    "sec:org811d6a1"
    "fig:orgfe8ff5e"
    "fig:Transient"
    "eq:Productivity_Function"
    "sec:orgef6a8f4"
    "sec:org0a0f3f9"
    "sec:orgb39e9d1"
    "sec:org6521533"
    "eq:FinalValue"
    "eq:FinalValue2"
    "eq:Capacity"
    "sec:org13e3493"
    "sec:org2f8ad47"
    "sec:org91b4eb5"
    "sec:org2fce266"
    "eq:CycleTime"
    "eq:ArtifactJ"
    "eq:Artifact1"
    "eq:Artifact2"
    "sec:orge8e9523"
    "sec:org30033e4"
    "sec:org21820d5"
    "sec:orgae8bb70"
    "sec:org3f82ecf"
    "sec:org5bb71bd"
    "sec:org33984cd"
    "sec:org70656f8"
    "sec:orgfa53465"
    "sec:org5b5bbbb"
    "sec:orgd1e7990"
    "sec:org7e95889"
    "sec:org8efc576"
    "sec:org86d2ec1"
    "sec:orgdea13ec")
   (LaTeX-add-bibliographies
    "/Users/ricmagno/Documents/References/library"))
 :latex)

