(TeX-add-style-hook
 "chapter"
 (lambda ()
   (TeX-add-to-alist 'LaTeX-provided-package-options
                     '(("inputenc" "-*-coding:utf-8-*-") ("fontenc" "T1") ("ulem" "normalem") ("geometry" "margin=2cm" "a4paper" "bindingoffset=0.2in" "left=1in" "right=1in" "top=1in" "bottom=1in" "footskip=.25in") ("biblatex" "backend=biber" "style=apa")))
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "nolinkurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperbaseurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperimage")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperref")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "href")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "path")
   (TeX-run-style-hooks
    "latex2e"
    "article"
    "art10"
    "inputenc"
    "fontenc"
    "graphicx"
    "grffile"
    "longtable"
    "wrapfig"
    "rotating"
    "ulem"
    "amsmath"
    "textcomp"
    "amssymb"
    "capt-of"
    "hyperref"
    "geometry"
    "biblatex"
    "tikz")
   (LaTeX-add-labels
    "sec:org2e2125b"
    "sec:org63ff675"
    "sec:orgd3ab43b"
    "sec:org8a57138"
    "sec:orgf75f072"
    "sec:orgeb19b82"
    "sec:orga589561"
    "sec:orga3d84d3"
    "sec:org9a32df3"
    "sec:org368b8ac"
    "sec:orgab0c258"
    "sec:orgc6b5cc9"
    "sec:org15be008"
    "sec:org8c09864"
    "sec:org9359f64"
    "fig:Schematic view of a flow of items through a queuing system"
    "eq:Little's Law"
    "eq:Little's Law average"
    "fig:Number of items in a queuing system versus time"
    "eq:Little's Law for operation management"
    "sec:org36d895b"
    "sec:org6d7914a"
    "sec:org7084a71"
    "sec:orge7d93f6"
    "eq:Critical WIP"
    "sec:orgb037dc0"
    "eq:Best cycle through"
    "eq:Best throughput"
    "sec:orgefeb215"
    "eq:Worst-case performance cycle through"
    "eq:Worst-case performance throughput"
    "eq:Practical worst-case performance cycle through"
    "fig:Cycle time versus WIP"
    "fig:throughput versus WIP worst- and best-case performance scenario"
    "sec:org23f0585"
    "eq:Law (Labor Capacity)"
    "sec:org52b9cf0"
    "tb:Classes of variability"
    "sec:org38db978"
    "sec:orgd325ed5"
    "sec:orgc8db730"
    "sec:org2dc8e52"
    "sec:org24455bc"
    "fig:Cycle time versus parallel batch size in batch production"
    "sec:org103880d"
    "sec:org640192f"
    "sec:org0f559ec"
    "fig:org8c5fe5a"
    "fig:org4b3d3c0"
    "fig:org0ae00ad"
    "sec:org90418d0"
    "sec:orgc02e18f"
    "eq:steady state"
    "eq:Step function in time domain P7"
    "sec:orgd6d90ff"
    "sec:orgc0cdefa"
    "sec:orge31e041"
    "fig:orgd59127f"
    "fig:Transient"
    "eq:Productivity_Function"
    "sec:orgfeff6fe"
    "sec:orgb1e5984"
    "sec:org21dbdb0"
    "sec:orgd71bf64"
    "eq:FinalValue"
    "eq:FinalValue2"
    "eq:Capacity"
    "sec:orgd9be29b"
    "sec:org53eccdf"
    "sec:org868a8d1"
    "sec:org7e30836"
    "eq:CycleTime"
    "eq:ArtifactJ"
    "eq:Artifact1"
    "eq:Artifact2"
    "sec:org00e1e0d"
    "sec:org3eefdd1"
    "sec:orga2acf92"
    "sec:org9317026"
    "sec:org1308e21"
    "sec:orgdf5efec"
    "sec:org5c29298"
    "sec:orge00d3cc"
    "sec:org5022206"
    "sec:org116ba6b"
    "sec:org7a194c2"
    "sec:orge442665"
    "sec:org30f568e"
    "sec:org87c1e79"
    "sec:org48bcbeb")
   (LaTeX-add-bibliographies
    "/Users/ricmagno/Documents/References/library"))
 :latex)

